server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/v1/users/**
            - id: catalog-service
              uri: http://catalog-service:8082
              predicates:
                - Path=/api/v1/catalog/**
            - id: uploader-service
              uri: http://uploader-service:8083
              predicates:
                - Path=/api/v1/upload/**
            - id: stream-service
              uri: http://stream-service:8085
              predicates:
                - Path=/api/v1/stream/**
            - id: notification-service
              uri: ws://notification-service:8086
              predicates:
                - Path=/notifications

jwt:
  secret: U2VjcmV0S2V5Rm9yRnVsbHN0YWNrTWljcm9zZXJ2aWNlc1ZpZGVvUGxhdGZvcm1Qcm9qZWN0